/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "AppWeb": {
      "type": "sst.cloudflare.StaticSite"
      "url": string
    }
    "Landing": {
      "type": "sst.cloudflare.Astro"
      "url": string
    }
    "OGCache": import("@cloudflare/workers-types").KVNamespace
    "OGFunction": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "OttoIo": import("@cloudflare/workers-types").Service
    "PreviewApi": import("@cloudflare/workers-types").Service
    "PreviewDB": import("@cloudflare/workers-types").D1Database
    "PreviewWeb": {
      "type": "sst.cloudflare.Astro"
      "url": string
    }
    "ShareStorage": import("@cloudflare/workers-types").R2Bucket
  }
}

import "sst"
export {}