import type { ForgeDocKind } from './types.ts';

export type ForgeDoc = {
	kind: ForgeDocKind;
	topic: string;
	title: string;
	summary: string;
	content: string;
};

type ForgeDocTopic = Omit<ForgeDoc, 'kind' | 'topic'>;

const FORGE_DOCS = {
	recipe: {
		'getting-started': {
			title: 'Create a recipe',
			summary: 'Create a reusable slash-command workflow.',
			content: `Recipes are Markdown instructions stored in .otto/recipes/<name>.md for project scope or ~/.config/otto/recipes/<name>.md for global scope. Names use lowercase letters, numbers, and hyphens.

Example:
forge({
  action: "create",
  kind: "recipe",
  name: "release-check",
  description: "Check release readiness",
  content: "Run focused tests and summarize blockers.",
  recipeAgent: "build",
  includeInHistory: true,
  oneShot: false,
  dryRun: true
})

Review the returned plan, then repeat without dryRun to write it.`,
		},
		frontmatter: {
			title: 'Recipe frontmatter',
			summary: 'Understand recipe metadata generated by Forge.',
			content: `A recipe may declare description, agent, includeInHistory, and oneShot. The body contains the instructions. Forge generates and validates the frontmatter from its typed inputs.

includeInHistory defaults to true. oneShot defaults to false. recipeAgent defaults to build. Tool approval policies still apply to one-shot recipes.`,
		},
	},
	skill: {
		'getting-started': {
			title: 'Create a skill',
			summary: 'Create a discoverable instruction bundle.',
			content: `Skills use a SKILL.md file under .otto/skills/<name>/ for project scope or ~/.config/otto/skills/<name>/ for global scope. Names use lowercase letters, numbers, and single hyphens.

Example:
forge({
  action: "create",
  kind: "skill",
  name: "bun-testing",
  description: "Write focused tests with Bun",
  content: "# Bun testing\n\nUse bun:test and keep fixtures isolated.",
  allowedTools: ["read", "shell"],
  dryRun: true
})`,
		},
		manifest: {
			title: 'SKILL.md contract',
			summary: 'Reference the supported skill frontmatter.',
			content: `SKILL.md requires YAML frontmatter with name and description, followed by Markdown instructions. allowed-tools is optional and stores a space-separated list.

Example:
---
name: "bun-testing"
description: "Write focused tests with Bun"
allowed-tools: "read shell"
---

# Bun testing

Use bun:test and keep fixtures isolated.`,
		},
	},
	agent: {
		'getting-started': {
			title: 'Create an agent',
			summary: 'Create an agent configuration and prompt.',
			content: `Project agents use .otto/agents.json and .otto/agents/<name>.md. Global agents use the equivalent paths under ~/.config/otto.

Example:
forge({
  action: "create",
  kind: "agent",
  name: "reviewer",
  description: "Review code without editing it",
  content: "Report concrete findings with file and line references.",
  tools: { firstClass: ["read", "search"], loadable: [] },
  dryRun: true
})`,
		},
		configuration: {
			title: 'Agent configuration',
			summary: 'Configure prompts, models, and tool groups.',
			content: `Agent inputs support description, content, provider, model, tools, and appendTools. tools replaces the configured firstClass/loadable groups. appendTools adds to inherited defaults. Forge stores prompts in a dedicated Markdown file and updates the scoped agents.json entry.

firstClass tools are sent directly to the model. loadable tools are advertised through load_tools and loaded on demand. Use forge({ action: "capabilities", kind: "agent" }) for the live project catalog, or provide query to filter it. The catalog includes built-in, plugin, and connected MCP tools with activation, source, risk, and availability metadata.`,
		},
	},
	'mcp-server': {
		'getting-started': {
			title: 'Add an MCP server',
			summary: 'Configure a local or remote MCP server.',
			content: `MCP servers can be project or global. Preview configuration with action plan or dryRun before writing it.

Example:
forge({
  action: "plan",
  targetAction: "create",
  kind: "mcp-server",
  name: "example",
  transport: "stdio",
  command: "bunx",
  args: ["example-mcp-server"]
})`,
		},
		transports: {
			title: 'MCP transports and lifecycle',
			summary: 'Configure stdio, HTTP, or SSE and manage lifecycle.',
			content: `stdio requires command and optionally args and env. http and sse require url and optionally headers. Set start: true on create/update to connect immediately. Use action enable or disable for configured servers. Use action execute with operation start, stop, or restart for lifecycle control. Use status, authenticate, reauthenticate, and logout for MCP OAuth lifecycle. Browser flows return authUrl; Copilot device flows return verificationUri and userCode while Forge polls in the daemon.`,
		},
	},
	provider: {
		management: {
			title: 'Provider management',
			summary: 'Create, edit, enable, disable, and remove providers.',
			content: `Provider controls are global. Use status to inspect one provider, create for a custom provider, update for custom providers or built-in overrides, enable/disable for availability, and remove to delete a configured custom provider or built-in override.

Custom providers require compatibility and baseURL on creation. Optional fields include label, family, apiKeyEnv, models, fastModels, allowAnyModel, and modelDiscovery. Use dryRun before mutations. Credentials belong to kind auth, not provider configuration.

models accepts model ID strings or structured model objects. A structured model can override the provider-wide transport for mixed gateways with provider.id (upstream model ID), provider.compatibility, provider.baseURL (or provider.api), provider.npm, and provider.family. Known npm bindings are @ai-sdk/openai, @ai-sdk/anthropic, @ai-sdk/google, @openrouter/ai-sdk-provider, @ai-sdk/openai-compatible, and ai-sdk-ollama. Prefer explicit compatibility; npm names select only these built-in adapters and never load arbitrary packages.

Example mixed gateway:
forge({
	action: "create",
	kind: "provider",
	name: "company-models",
	compatibility: "openai-compatible",
	family: "default",
	baseURL: "https://models.example.com/v1",
	models: [
		{ id: "gpt-5", provider: { compatibility: "openai", baseURL: "https://models.example.com/openai/v1", family: "openai" } },
		{ id: "claude-sonnet", provider: { id: "claude-sonnet-4", compatibility: "anthropic", baseURL: "https://models.example.com/anthropic", family: "anthropic" } }
	],
	dryRun: true
})`,
		},
	},
	auth: {
		management: {
			title: 'Provider authentication',
			summary: 'Manage API keys, OAuth, reauthentication, and logout.',
			content: `Use kind auth with the provider id in name. status returns only safe metadata and never tokens. authenticate and reauthenticate accept authMethod api-key or oauth. API-key authentication requires apiKey and never returns it. OAuth returns authUrl and, for device flows, userCode while Forge polls securely in the daemon. Use logout or remove to delete credentials.

OpenAI supports browser or device OAuth. Anthropic and xAI support browser OAuth. Copilot, Kimi, and OttoRouter use device OAuth. Logging out of OttoRouter also disables the managed remote-control tunnel.`,
		},
	},
	tunnel: {
		lifecycle: {
			title: 'Tunnel lifecycle',
			summary: 'Inspect, enable, disable, start, stop, or restart tunnels.',
			content: `Use kind tunnel with action status, enable, disable, or execute. execute requires operation start, stop, or restart. tunnelMode defaults to managed and tunnelScope defaults to remote-control. project-share scope requires projectId. Managed remote-control tunnels persist their desired enabled state across daemon restarts. Use dryRun to preview lifecycle changes.`,
		},
	},
	plugin: {
		manifest: {
			title: 'Plugin manifest',
			summary: 'Define an installable Otto plugin package.',
			content: `Plugins use otto.plugin.json. name and version are required. Supported contributions include skills, recipes, agents, mcpServers, commands, and native tools.

Example:
{
  "name": "project-tools",
  "version": "1.0.0",
  "description": "Project workflow helpers",
  "skills": [{ "name": "release", "path": "skills/release/SKILL.md" }],
  "commands": {
    "check": { "command": "bun", "args": ["test"] }
  }
}

Forge treats local plugins as first-class editable packages. action create builds an unpublished project or global plugin locally. action install installs a registry plugin or a local directory. status, update, remove, enable, disable, search, and validate manage the full lifecycle. Registry-managed plugins are not edited in place; install or create a local fork first.

Example:
forge({
	action: "create",
	kind: "plugin",
	scope: "project",
	name: "project-tools",
	version: "0.1.0",
	description: "Local project automation"
})`,
		},
		capabilities: {
			title: 'Plugin-owned capabilities',
			summary:
				'Create and edit recipes, skills, and agents inside local plugins.',
			content: `Set plugin when creating, updating, or removing a recipe, skill, or agent contribution. Forge writes the capability source inside the plugin, updates otto.plugin.json, validates the result, and refreshes skill/tool discovery.

Example:
forge({
	action: "create",
	kind: "recipe",
	plugin: "project-tools",
	name: "release-check",
	description: "Check release readiness",
	content: "Run focused tests and summarize blockers."
})

Inventory reports source, plugin ownership, mutability, manifest paths, and contributed recipes, skills, agents, commands, tools, and MCP servers.`,
		},
		commands: {
			title: 'Plugin commands',
			summary: 'Create slash commands backed by visible terminals.',
			content: `A plugin command is Otto's terminal-backed slash-command primitive. Commands from enabled plugins are exposed as /<plugin> <command> and run in visible terminals. A command requires command and may include label, description, args, env, cwd, typed parameters, and allowExtraArgs. Forge can plan/create/update/remove commands in installed plugin manifests and execute enabled commands.

Create a slash command:
forge({
	action: "create",
	kind: "plugin-command",
	plugin: "project-tools",
	commandName: "check",
	command: "bun",
	args: ["test"],
	description: "Run project tests",
	dryRun: true
})

Execute it directly:
forge({
  action: "execute",
  kind: "plugin-command",
  plugin: "project-tools",
  commandName: "check",
  commandArgs: {}
})`,
		},
		tools: {
			title: 'Native plugin tools',
			summary: 'Declare isolated TypeScript or JavaScript tools.',
			content: `Each native tool declares name, entry, description, inputSchema, optional outputSchema, effects, optional secrets, and timeoutMs. Entries must remain inside the plugin directory. Supported effects are workspace-read, workspace-write, process, network, secrets, and external-write. A tool declaring secrets must include the secrets effect.`,
		},
	},
	'plugin-tool': {
		management: {
			title: 'Native plugin tool lifecycle',
			summary: 'Create, edit, validate, execute, and delete native tools.',
			content: `Native tools live inside local Otto plugins. Use kind "plugin-tool" with plugin and toolName. create/update accepts content for the TypeScript implementation, entry, description, inputSchema, optional outputSchema, effects, secret declarations, and timeoutMs. validate checks the complete plugin and execute accepts toolInput. remove deletes the manifest contribution and its unshared source file.

Secrets are declarations that map a logical name to an environment variable; never put secret values in content, env, or toolInput. Registry-managed plugins must be forked or installed locally before their tools can be edited.`,
		},
	},
	app: {
		'getting-started': {
			title: 'Mini App availability',
			summary: 'Check the installed Mini App authoring contract.',
			content: `This Otto version does not expose a stable Mini App manifest, runtime, or Forge app mutation action. Do not create app manifests based on proposal documents. Use visual outputs or a normal project application until a versioned app contract is available.`,
		},
		permissions: {
			title: 'Mini App permissions',
			summary: 'Check the status of the Mini App permission contract.',
			content: `Mini App permissions are not a stable extension contract in this Otto version. Generated browser code must not receive Otto credentials, environment secrets, unrestricted filesystem or shell access, Docker sockets, or direct host process access. Wait for a versioned host bridge and permission schema before targeting Otto capabilities.`,
		},
	},
} as const satisfies Record<ForgeDocKind, Record<string, ForgeDocTopic>>;

function listTopics(kind: ForgeDocKind) {
	return Object.entries(FORGE_DOCS[kind]).map(([topic, document]) => ({
		topic,
		title: document.title,
		summary: document.summary,
	}));
}

function searchDocs(kind: ForgeDocKind | undefined, query: string) {
	const terms = query.toLowerCase().split(/\s+/).filter(Boolean);
	const kinds = kind ? [kind] : (Object.keys(FORGE_DOCS) as ForgeDocKind[]);
	const matches: ForgeDoc[] = [];
	for (const docKind of kinds) {
		for (const [topic, document] of Object.entries(FORGE_DOCS[docKind])) {
			const haystack = [
				docKind,
				topic,
				document.title,
				document.summary,
				document.content,
			]
				.join('\n')
				.toLowerCase();
			if (!terms.every((term) => haystack.includes(term))) continue;
			matches.push({ kind: docKind, topic, ...document });
		}
	}
	return {
		query,
		matches: matches.slice(0, 10),
		truncated: matches.length > 10,
	};
}

export function getForgeDocs(
	kind?: ForgeDocKind,
	topic?: string,
	query?: string,
) {
	const normalizedQuery = query?.trim();
	if (topic?.trim() && normalizedQuery) {
		throw new Error(
			'Use either topic for exact lookup or query for docs search',
		);
	}
	if (normalizedQuery) return searchDocs(kind, normalizedQuery);

	if (!kind) {
		if (topic?.trim())
			throw new Error('kind is required when topic is provided');
		return {
			kinds: (Object.keys(FORGE_DOCS) as ForgeDocKind[]).map((docKind) => ({
				kind: docKind,
				topics: listTopics(docKind),
			})),
		};
	}

	const normalizedTopic = topic?.trim().toLowerCase();
	if (!normalizedTopic) return { kind, topics: listTopics(kind) };

	const document = FORGE_DOCS[kind][
		normalizedTopic as keyof (typeof FORGE_DOCS)[typeof kind]
	] as ForgeDocTopic | undefined;
	if (!document) {
		throw new Error(
			`Unknown Forge docs topic '${normalizedTopic}' for ${kind}. Available topics: ${Object.keys(FORGE_DOCS[kind]).join(', ')}`,
		);
	}

	return { kind, topic: normalizedTopic, ...document } satisfies ForgeDoc;
}
