import type { ForgeDocKind } from './types.ts';

export type ForgeDoc = {
	kind: ForgeDocKind;
	topic: string;
	title: string;
	summary: string;
	content: string;
};

type ForgeDocTopic = Omit<ForgeDoc, 'kind' | 'topic'>;

const FORGE_DOCS = {
	recipe: {
		'getting-started': {
			title: 'Create a recipe',
			summary: 'Create a reusable slash-command workflow.',
			content: `Recipes are Markdown instructions stored in .otto/recipes/<name>.md for project scope or ~/.config/otto/recipes/<name>.md for global scope. Names use lowercase letters, numbers, and hyphens.

Example:
forge({
  action: "create",
  kind: "recipe",
  name: "release-check",
  description: "Check release readiness",
  content: "Run focused tests and summarize blockers.",
  recipeAgent: "build",
  includeInHistory: true,
  oneShot: false,
  dryRun: true
})

Review the returned plan, then repeat without dryRun to write it.`,
		},
		frontmatter: {
			title: 'Recipe frontmatter',
			summary: 'Understand recipe metadata generated by Forge.',
			content: `A recipe may declare description, agent, includeInHistory, and oneShot. The body contains the instructions. Forge generates and validates the frontmatter from its typed inputs.

includeInHistory defaults to true. oneShot defaults to false. recipeAgent defaults to build. Tool approval policies still apply to one-shot recipes.`,
		},
	},
	skill: {
		'getting-started': {
			title: 'Create a skill',
			summary: 'Create a discoverable instruction bundle.',
			content: `Skills use a SKILL.md file under .otto/skills/<name>/ for project scope or ~/.config/otto/skills/<name>/ for global scope. Names use lowercase letters, numbers, and single hyphens.

Example:
forge({
  action: "create",
  kind: "skill",
  name: "bun-testing",
  description: "Write focused tests with Bun",
  content: "# Bun testing\n\nUse bun:test and keep fixtures isolated.",
  allowedTools: ["read", "shell"],
  dryRun: true
})`,
		},
		manifest: {
			title: 'SKILL.md contract',
			summary: 'Reference the supported skill frontmatter.',
			content: `SKILL.md requires YAML frontmatter with name and description, followed by Markdown instructions. allowed-tools is optional and stores a space-separated list.

Example:
---
name: "bun-testing"
description: "Write focused tests with Bun"
allowed-tools: "read shell"
---

# Bun testing

Use bun:test and keep fixtures isolated.`,
		},
	},
	agent: {
		'getting-started': {
			title: 'Create an agent',
			summary: 'Create an agent configuration and prompt.',
			content: `Project agents use .otto/agents.json and .otto/agents/<name>.md. Global agents use the equivalent paths under ~/.config/otto.

Example:
forge({
  action: "create",
  kind: "agent",
  name: "reviewer",
  description: "Review code without editing it",
  content: "Report concrete findings with file and line references.",
  tools: { firstClass: ["read", "search"], loadable: [] },
  dryRun: true
})`,
		},
		configuration: {
			title: 'Agent configuration',
			summary: 'Configure prompts, models, and tool groups.',
			content: `Agent inputs support description, content, provider, model, tools, and appendTools. tools replaces the configured firstClass/loadable groups. appendTools adds to inherited defaults. Forge stores prompts in a dedicated Markdown file and updates the scoped agents.json entry.

firstClass tools are sent directly to the model. loadable tools are advertised through load_tools and loaded on demand. Use forge({ action: "capabilities", kind: "agent" }) for the live project catalog, or provide query to filter it. The catalog includes built-in, plugin, and connected MCP tools with activation, source, risk, and availability metadata.`,
		},
	},
	'mcp-server': {
		'getting-started': {
			title: 'Add an MCP server',
			summary: 'Configure a local or remote MCP server.',
			content: `MCP servers can be project or global. Preview configuration with action plan or dryRun before writing it.

Example:
forge({
  action: "plan",
  targetAction: "create",
  kind: "mcp-server",
  name: "example",
  transport: "stdio",
  command: "bunx",
  args: ["example-mcp-server"]
})`,
		},
		transports: {
			title: 'MCP transports and lifecycle',
			summary: 'Configure stdio, HTTP, or SSE and manage lifecycle.',
			content: `stdio requires command and optionally args and env. http and sse require url and optionally headers. Set start: true on create/update to connect immediately. Use action enable or disable for configured servers. Use action execute with operation start, stop, or restart for lifecycle control. Use status, authenticate, reauthenticate, and logout for MCP OAuth lifecycle. Browser flows return authUrl; Copilot device flows return verificationUri and userCode while Forge polls in the daemon.`,
		},
	},
	provider: {
		management: {
			title: 'Provider management',
			summary: 'Create, edit, enable, disable, and remove providers.',
			content: `Provider controls are global. Use status to inspect one provider, create for a custom provider, update for custom providers or built-in overrides, enable/disable for availability, and remove to delete a configured custom provider or built-in override.

Custom providers require compatibility and baseURL on creation. Optional fields include label, family, apiKeyEnv, models, fastModels, allowAnyModel, and modelDiscovery. Use dryRun before mutations. Credentials belong to kind auth, not provider configuration.`,
		},
	},
	auth: {
		management: {
			title: 'Provider authentication',
			summary: 'Manage API keys, OAuth, reauthentication, and logout.',
			content: `Use kind auth with the provider id in name. status returns only safe metadata and never tokens. authenticate and reauthenticate accept authMethod api-key or oauth. API-key authentication requires apiKey and never returns it. OAuth returns authUrl and, for device flows, userCode while Forge polls securely in the daemon. Use logout or remove to delete credentials.

OpenAI supports browser or device OAuth. Anthropic and xAI support browser OAuth. Copilot, Kimi, and OttoRouter use device OAuth. Logging out of OttoRouter also disables the managed remote-control tunnel.`,
		},
	},
	tunnel: {
		lifecycle: {
			title: 'Tunnel lifecycle',
			summary: 'Inspect, enable, disable, start, stop, or restart tunnels.',
			content: `Use kind tunnel with action status, enable, disable, or execute. execute requires operation start, stop, or restart. tunnelMode defaults to managed and tunnelScope defaults to remote-control. project-share scope requires projectId. Managed remote-control tunnels persist their desired enabled state across daemon restarts. Use dryRun to preview lifecycle changes.`,
		},
	},
	plugin: {
		manifest: {
			title: 'Plugin manifest',
			summary: 'Define an installable Otto plugin package.',
			content: `Plugins use otto.plugin.json. name and version are required. Supported contributions include skills, recipes, agents, mcpServers, commands, and native tools.

Example:
{
  "name": "project-tools",
  "version": "1.0.0",
  "description": "Project workflow helpers",
  "skills": [{ "name": "release", "path": "skills/release/SKILL.md" }],
  "commands": {
    "check": { "command": "bun", "args": ["test"] }
  }
}

Use otto plugins validate <plugin-directory> to validate a local package. Forge does not currently create or mutate plugin packages.`,
		},
		commands: {
			title: 'Plugin commands',
			summary: 'Declare and execute visible host commands.',
			content: `A plugin command requires command and may include label, description, args, env, cwd, typed parameters, allowExtraArgs, and fallback. Commands from enabled plugins run in visible terminals.

Example:
forge({
  action: "execute",
  kind: "plugin-command",
  plugin: "project-tools",
  commandName: "check",
  commandArgs: {}
})`,
		},
		tools: {
			title: 'Native plugin tools',
			summary: 'Declare isolated TypeScript or JavaScript tools.',
			content: `Each native tool declares name, entry, description, inputSchema, optional outputSchema, effects, optional secrets, and timeoutMs. Entries must remain inside the plugin directory. Supported effects are workspace-read, workspace-write, process, network, secrets, and external-write. A tool declaring secrets must include the secrets effect.`,
		},
	},
	app: {
		'intent-and-artifacts': {
			title: 'Normal work, artifacts, and Mini Apps',
			summary: 'Preserve the user’s requested output and installation intent.',
			content: `Normal project work is the default. Do not turn ordinary requests for websites, apps, landing pages, dashboards, components, scripts, charts, or visualizations into Forge calls, Artifacts, or Otto Mini Apps. Forge documentation is reference material and never overrides the user’s request.

Implement the request in the user's current project unless the user explicitly asks for a chat Artifact or Otto-specific extension. Use a chat Artifact only when the user explicitly asks for an artifact, an in-chat interactive output, a detachable chat result, or clearly chooses that presentation after it is offered. Use a Mini App only when the user explicitly asks for an Otto Mini App, an app installed inside Otto, project/global installation, or promotion of existing work into a Mini App.

Examples:
- "Create a landing page" → normal work in the current project.
- "Build an app for tracking expenses" → normal application in the current project.
- "Visualize this CSV interactively" → normal project implementation unless the user asks for an in-chat Artifact.
- "Show this as an interactive Artifact in chat" → Artifact.
- "Build an Otto app for exploring PRs" → Mini App.
- "Save this dashboard so I can reopen it in every project" → global Mini App.

When intent is ambiguous, preserve normal project work. Never silently route a request through Forge or install an Otto extension.`,
		},
		'getting-started': {
			title: 'Create a Mini App',
			summary: 'Create and build a project-local React Mini App.',
			content: `Mini Apps are first-class application packages, not raw index.html files. Project apps currently live under .otto/apps/<app-id>/ and require app.json plus a default-exported React component.

Minimum layout:
.otto/apps/project-health/
	app.json
	src/main.tsx

Build workflow:
1. Create app.json and source files with the normal filesystem tools.
2. Load the loadable mini_app tool with load_tools.
3. Run mini_app({ action: "build", root: ".otto/apps/project-health" }).
4. The result contains an immutable revision and previewPath; Otto renders it as a Mini App card and sandboxed preview.

Use action "present" only to validate source or attach an already-running localhost preview. Saved project apps are discovered from .otto/apps. Saved global apps are discovered from ~/.config/otto/apps when availability.global is true. Forge does not yet create or publish Mini Apps; storage, host capabilities, plugins, and public publishing are not available in the current contract.`,
		},
		manifest: {
			title: 'Mini App manifest',
			summary: 'Reference the versioned app.json contract.',
			content: `app.json is strict and currently supports schemaVersion 1 with runtime "otto-react".

Example:
{
	"$schema": "otto://schemas/mini-app/v1",
	"schemaVersion": 1,
	"id": "project-health",
	"name": "Project Health",
	"description": "Inspect the active project",
	"runtime": "otto-react",
	"entry": "src/main.tsx",
	"availability": {
		"global": false,
		"project": true,
		"requiresProject": true
	},
	"permissions": [],
	"capabilities": [],
	"placements": ["apps", "project"]
}

IDs use lowercase letters, numbers, and hyphens. entry and optional icon are relative paths that must remain inside the app directory. Supported placements are apps, project, and commandPalette. Permissions and capabilities are declared for forward compatibility but no host bridge is available yet.`,
		},
		runtime: {
			title: 'Curated Mini App runtime',
			summary: 'Use React, Motion, icons, CSS, and local assets.',
			content: `The otto-react runtime uses Bun embedded in Otto; users do not need Bun, Node.js, or npm installed. The entry module must default-export a React component. Otto provides the document and React root.

Example:
import { motion } from "motion/react";
import { Activity } from "lucide-react";
import "./styles.css";

export default function App() {
	return (
		<motion.main initial={{ opacity: 0 }} animate={{ opacity: 1 }}>
			<Activity />
			<h1>Project Health</h1>
		</motion.main>
	);
}

Curated package imports are react, react-dom, motion, and lucide-react, including their subpath exports. Relative TypeScript, TSX, JavaScript, JSX, CSS, and local asset imports are bundled. Other bare package imports are rejected. Custom CSS, responsive design, CSS variables, transitions, and Motion animations are supported.`,
		},
		building: {
			title: 'Build and preview Mini Apps',
			summary: 'Compile immutable app revisions with the loadable tool.',
			content: `Load the tool on demand:
load_tools({ tools: ["mini_app"] })

Then compile:
mini_app({
	action: "build",
	root: ".otto/apps/project-health"
})

Builds are content-addressed by the validated source tree and stored under .otto/cache/mini-apps/<app-id>/<revision-id>/. Rebuilding unchanged source reuses the immutable build. Editing source and building again creates a new revision.

The Apps panel discovers project apps from .otto/apps and global apps from ~/.config/otto/apps. Opening a saved app builds its current revision on demand and launches it in the Mini App viewer.

The compiler limits source files, source bytes, manifest size, and build output size. It rejects symbolic links, paths outside the project, and package imports outside the curated runtime.`,
		},
		permissions: {
			title: 'Mini App permissions',
			summary: 'Understand the current Mini App security boundary.',
			content: `Generated Mini App code is untrusted browser UI. Preview assets use a restrictive Content Security Policy and run in a sandboxed iframe without same-origin access. Network connections are disabled for curated builds.

Mini Apps must not receive Otto credentials, provider keys, environment secrets, unrestricted filesystem or shell access, Docker sockets, or direct host process access. The manifest can record future permission and capability IDs, but the host bridge is not implemented in this version. Do not simulate privileged access in browser code or call daemon APIs directly. Wait for versioned typed capabilities and approval policies.`,
		},
	},
} as const satisfies Record<ForgeDocKind, Record<string, ForgeDocTopic>>;

function listTopics(kind: ForgeDocKind) {
	return Object.entries(FORGE_DOCS[kind]).map(([topic, document]) => ({
		topic,
		title: document.title,
		summary: document.summary,
	}));
}

function searchDocs(kind: ForgeDocKind | undefined, query: string) {
	const terms = query.toLowerCase().split(/\s+/).filter(Boolean);
	const kinds = kind ? [kind] : (Object.keys(FORGE_DOCS) as ForgeDocKind[]);
	const matches: ForgeDoc[] = [];
	for (const docKind of kinds) {
		for (const [topic, document] of Object.entries(FORGE_DOCS[docKind])) {
			const haystack = [
				docKind,
				topic,
				document.title,
				document.summary,
				document.content,
			]
				.join('\n')
				.toLowerCase();
			if (!terms.every((term) => haystack.includes(term))) continue;
			matches.push({ kind: docKind, topic, ...document });
		}
	}
	return {
		query,
		matches: matches.slice(0, 10),
		truncated: matches.length > 10,
	};
}

export function getForgeDocs(
	kind?: ForgeDocKind,
	topic?: string,
	query?: string,
) {
	const normalizedQuery = query?.trim();
	if (topic?.trim() && normalizedQuery) {
		throw new Error(
			'Use either topic for exact lookup or query for docs search',
		);
	}
	if (normalizedQuery) return searchDocs(kind, normalizedQuery);

	if (!kind) {
		if (topic?.trim())
			throw new Error('kind is required when topic is provided');
		return {
			kinds: (Object.keys(FORGE_DOCS) as ForgeDocKind[]).map((docKind) => ({
				kind: docKind,
				topics: listTopics(docKind),
			})),
		};
	}

	const normalizedTopic = topic?.trim().toLowerCase();
	if (!normalizedTopic) return { kind, topics: listTopics(kind) };

	const document = FORGE_DOCS[kind][
		normalizedTopic as keyof (typeof FORGE_DOCS)[typeof kind]
	] as ForgeDocTopic | undefined;
	if (!document) {
		throw new Error(
			`Unknown Forge docs topic '${normalizedTopic}' for ${kind}. Available topics: ${Object.keys(FORGE_DOCS[kind]).join(', ')}`,
		);
	}

	return { kind, topic: normalizedTopic, ...document } satisfies ForgeDoc;
}
